version: "3.8"
services:
  db_ice:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_ICE_NAME}"
      MYSQL_USER: "${DB_ICE_USER}"
      MYSQL_PASSWORD: "${DB_ICE_PASS}"
    volumes:
      - db_ice_data:/var/lib/mysql
    networks:
      - dolinet

  dolibarr_ice:
    image: dolibarr/dolibarr:latest
    depends_on:
      - db_ice
    restart: always
    environment:
      DOLI_DB_HOST: db_ice
      DOLI_DB_USER: "${DB_ICE_USER}"
      DOLI_DB_PASSWORD: "${DB_ICE_PASS}"
      DOLI_DB_NAME: "${DB_ICE_NAME}"
      DOLI_MAIN_URL_ROOT: "https://${DOLI_ICE_DOMAIN}"
    volumes:
      - dolibarr_ice_docs:/var/www/html/documents
      - dolibarr_ice_custom:/var/www/html/custom
    networks:
      - dolinet

volumes:
  db_ice_data:
  dolibarr_ice_docs:
  dolibarr_ice_custom:

networks:
  dolinet:
    external: true
