version: "3.8"
services:
  db_ice:
    image: mariadb:10.6
    container_name: ice_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_ICE_NAME:-dolibarr}"
      MYSQL_USER: "${DB_ICE_USER:-dolibarruser}"
      MYSQL_PASSWORD: "${DB_ICE_PASS:-dolipass}"
    volumes:
      - ice_db_data:/var/lib/mysql
    networks:
      - ice_net

  dolibarr_ice:
    image: dolibarr/dolibarr:latest
    container_name: ice_dolibarr
    depends_on:
      - db_ice
    restart: unless-stopped
    environment:
      DOLI_DB_HOST: db_ice
      DOLI_DB_USER: "${DB_ICE_USER:-dolibarruser}"
      DOLI_DB_PASSWORD: "${DB_ICE_PASS:-dolipass}"
      DOLI_DB_NAME: "${DB_ICE_NAME:-dolibarr}"
      DOLI_MAIN_URL_ROOT: "https://ice.IndrayaniNaturals.in"
    volumes:
      - ice_dolibarr_docs:/var/www/html/documents
      - ice_dolibarr_custom:/var/www/html/custom
    expose:
      - "80"
    networks:
      - ice_net

volumes:
  ice_db_data:
  ice_dolibarr_docs:
  ice_dolibarr_custom:

networks:
  ice_net:
    external: true
