version: "3.8"
services:
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./webroot:/var/www/html/.well-known/acme-challenge:rw
      - letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
    networks:
      - dolinet

  # ephemeral certbot service can be run manually to obtain certs (see below).
  # optionally you can enable a renew service here, but we'll show a cron method.

volumes:
  letsencrypt:

networks:
  dolinet:
    external: true
