version: "3.8"
services:
  db_spice:
    image: mariadb:10.6
    container_name: spice_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_SPICE_NAME:-dolibarr}"
      MYSQL_USER: "${DB_SPICE_USER:-dolibarruser}"
      MYSQL_PASSWORD: "${DB_SPICE_PASS:-dolipass}"
    volumes:
      - spice_db_data:/var/lib/mysql
    networks:
      - spice_net

  dolibarr_spice:
    image: dolibarr/dolibarr:latest
    container_name: spice_dolibarr
    depends_on:
      - db_spice
    restart: unless-stopped
    environment:
      DOLI_DB_HOST: db_spice
      DOLI_DB_USER: "${DB_SPICE_USER:-dolibarruser}"
      DOLI_DB_PASSWORD: "${DB_SPICE_PASS:-dolipass}"
      DOLI_DB_NAME: "${DB_SPICE_NAME:-dolibarr}"
      DOLI_MAIN_URL_ROOT: "https://spice.IndrayaniNaturals.in"
    volumes:
      - spice_dolibarr_docs:/var/www/html/documents
      - spice_dolibarr_custom:/var/www/html/custom
    expose:
      - "80"
    networks:
      - spice_net

volumes:
  spice_db_data:
  spice_dolibarr_docs:
  spice_dolibarr_custom:

networks:
  spice_net:
    external: true
